### ISSUE TITLE
adding network parameters

### ISSUE THREAD

**Issue by ya-zero** [tnaganawa/ansible-collections-tungstenfabric#1]
I suggest adding the ability to change the default parameters   for virtual_network  Gateway and Service Address (exaple : contrail set last addres in subnet ,  for /24 contrail set .254 , .253))  , if i'm need gatewa x.x.x.1  service x.x.x.2 ?   . 
Also suggest adding  enable/disable dns/dhcp  , if need non dhcp network.

p.s. rest api attr
"dns_server_address": "x.x.x.x",
"enable_dhcp": true,
"default_gateway": "x.x.x.x",

**Comment by tnaganawa** [comment]
Hi, @ya-zero, 

Thanks for the suggestion.

I added several parameters to the main branch.
```
 addr_from_start <- when this paramter is set to true, vRouter will assign IP address from .1, .2 ...
 dns_server_address
 enable_dhcp
 default_gateway
 dns_nameservers
```

Could you try the updated module?

Best Regards,
Tatsuya

**Comment by ya-zero** [comment]
contrail gui  (xml)
![image](https://user-images.githubusercontent.com/30143651/107343143-1dc41c00-6ad2-11eb-82f9-3686e19eb3bb.png)

contrail gui edit network
![image](https://user-images.githubusercontent.com/30143651/107343375-4b10ca00-6ad2-11eb-8455-27a174846d9d.png)





changed: [127.0.0.1] => (item={'key': 'peering', 'value': {'name': 'bgp_as_service_test_tanagava', 'subnet': '10.10.32.0', 'subnet_prefix': 24, 'dns_server_address': '10.10.32.2', 'default_gateway': '10.10.32.1', 'dns_nameservers': ['10.7.21.11', '10.7.21.12'], 'import_route_target_list': ['target:64512:102', 'target:64512:104', 'target:64512:106', 'target:64512:108'], 'export_route_target_list': ['target:64512:101', 'target:64512:103', 'target:64512:105', 'target:64512:107'], 'project': 'admin', 'rpf': False, 'enable_dhcp': False}}) => {
    "ansible_loop_var": "item",
    "changed": true,
    "invocation": {
        "module_args": {
            "addr_from_start": false,
            "allow_transit": null,
            "controller_ip": "10.193.18.240",
            "default_gateway": null,
            "display_name": null,
            "dns_nameservers": null,
            "dns_server_address": null,
            "domain": "default-domain",
            "enable_dhcp": null,
            "export_route_target_list": [
                "target:64512:101",
                "target:64512:103",
                "target:64512:105",
                "target:64512:107"
            ],
            "fabric_snat": null,
            "flood_unknown_unicast": null,
            "forwarding_mode": null,
            "global_object": null,
            "igmp_enable": null,
            "import_route_target_list": [
                "target:64512:102",
                "target:64512:104",
                "target:64512:106",
                "target:64512:108"
            ],
            "ip_fabric_forwarding": null,
            "mac_learning_enabled": null,
            "max_flows": null,
            "name": "bgp_as_service_test_tanagava",
            "network_policy_refs": null,
            "password": "contrail123",
            "port_security_enabled": null,
            "project": "admin",
            "route_target_list": null,
            "rpf": null,
            "state": "present",
            "subnet": "10.10.32.0",
            "subnet_prefix": 24,
            "tag_refs": null,
            "username": "admin",
            "uuid": null,
            "virtual_network_category": null,
            "vxlan_network_identifier": null
        }
    },
    "item": {
        "key": "peering",
        "value": {
            "default_gateway": "10.10.32.1",
            "dns_nameservers": [
                "10.7.21.11",
                "10.7.21.12"
            ],
            "dns_server_address": "10.10.32.2",
            "enable_dhcp": false,
            "export_route_target_list": [
                "target:64512:101",
                "target:64512:103",
                "target:64512:105",
                "target:64512:107"
            ],
            "import_route_target_list": [
                "target:64512:102",
                "target:64512:104",
                "target:64512:106",
                "target:64512:108"
            ],
            "name": "bgp_as_service_test_tanagava",
            "project": "admin",
            "rpf": false,
            "subnet": "10.10.32.0",
            "subnet_prefix": 24
        }
    },
    "message": "{\"configData\":{\"virtual-network\":{\"fq_name\":[\"default-domain\",\"admin\",\"bgp_as_service_test_tanagava\"],\"parent_uuid\":\"0278db5d-0274-49c7-9295-a3cf744f0c33\",\"parent_href\":\"http://10.193.18.241:8082/project/0278db5d-0274-49c7-9295-a3cf744f0c33\",\"parent_type\":\"project\",\"uuid\":\"56170948-dc3c-4102-af80-e25f1c491074\",\"href\":\"http://10.193.18.241:8082/virtual-network/56170948-dc3c-4102-af80-e25f1c491074\",\"name\":\"bgp_as_service_test_tanagava\"}},\"otherData\":[[null,[]],null]}",
